export const GET_ALL_IMAGE_REQUEST = 'GET_ALL_IMAGE_REQUEST';
export const GET_ALL_IMAGE_SUCCESS = 'GET_ALL_IMAGE_SUCCESS';
export const GET_ALL_IMAGE_FAIL = 'GET_ALL_IMAGE_FAIL';

export const GET_IMAGE_BY_FILENAME_REQUEST = 'GET_IMAGE_BY_FILENAME_REQUEST';
export const GET_IMAGE_BY_FILENAME_SUCCESS = 'GET_IMAGE_BY_FILENAME_SUCCESS';
export const GET_IMAGE_BY_FILENAME_FAIL = 'GET_IMAGE_BY_FILENAME_FAIL';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';
